id: int
index: int
title: string
primary: boolean
type: string
options: array
contactOptions: array
hidden: boolean
symbol: string
systemColumnType: string
autoNumberFormat: autonumberformat
tags: array
validation: boolean
width: int
format: string
filter: Filter
locked: boolean
lockedForUser: boolean